### PR TITLE
Fix OverloadedLists suggestion as documented in #114

### LINKED ISSUE #114: Incorrect suggestions with OverloadedLists
``` Haskell
{-# LANGUAGE OverloadedLists #-}
module Baz where

import Data.Foldable

foo :: Foldable t => t a -> t a
foo = id

bar = foo (True:[])
```

HLint suggests: 

```
Warning: Use list literal
Found:
  True : []
Why not:
  [True]
```

This will prevent the program from typechecking due to the ambiguity introduced by OverloadedLists

### PR DESCRIPTION
**Pull request by kk-hainq**
Fixes #114.

@ndmitchell I wonder if I should add a test for this case?

### CODE REVIEW

File: src/Hint/List.hs [hunk 1]
```diff
@@ -168,12 +170,12 @@ isAppend :: View a App2 => a -> Bool
...
 
-checks ::[(String, Bool -> LHsExpr GhcPs -> Maybe (LHsExpr GhcPs, [(String, R.SrcSpan)], String))]
-checks = let (*) = (,) in drop1 -- see #174
+checks :: [String] -> [(String, Bool -> LHsExpr GhcPs -> Maybe (LHsExpr GhcPs, [(String, R.SrcSpan)], String))]
+checks exts = let (*) = (,) in drop1 -- see #174
   [ "Use string literal" * useString
-  , "Use list literal" * useList
   , "Use :" * useCons
   ]
+  <> ["Use list literal" * useList | "OverloadedLists" `notElem` exts] -- see #114
```
Comment (ndmitchell) [inline src/Hint/List.hs:178]: Can we pull out the existence or otherwise of OverloadedLists as a boolean and sent it down from the top, instead of just the full list of extensions.

**Review by ndmitchell — COMMENTED** [review]
Thanks for the diff, looks good. Definitely wants a test though as its subtle and easy to break. I imagine a line in the `<test>` block at the top of this file will be sufficient - something like:

```
{-# LANGUAGE OverloadedLists #-} \
foo = True:[]
```

File: src/Hint/List.hs (hunk 1 above)
Comment (kk-hainq) [reply src/Hint/List.hs]: Thank you for the review. I've pushed 2 new commits to address both.

File: src/Hint/List.hs [hunk 2]
```diff
@@ -67,11 +69,14 @@ import Language.Haskell.GhclibParserEx.GHC.Types.Name.Reader
 
 
 listHint :: DeclHint
-listHint _ _ = listDecl
+listHint _ modu = listDecl overloadedListsOn
+  where
+    exts = nubOrd $ concatMap snd (languagePragmas (pragmas (ghcAnnotations modu)))
```
Comment (ndmitchell) [inline src/Hint/List.hs:74]: Why the `nubOrd` here? It is moderately expensive, and I can't see any use for it

**Review by ndmitchell — COMMENTED** [review]
One final question about a nubOrd, but otherwise looks good

File: src/Hint/List.hs (hunk 2 above)
Comment (kk-hainq) [reply src/Hint/List.hs]: Nice catch! It was originally used to pass down a clean `exts` to the following functions. Don't need it anymore for just `overloadedListsOn`, I have removed it in the latest commit.

**Comment by ndmitchell** [comment]
Thanks!
